name: CI/CD Pipeline

on:
  push:
    branches:
      - "feature/*"
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: |
          pip install -r backend/requirements.txt
          pip install pytest pytest-cov

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/backend" >> $GITHUB_ENV

      - name: Run tests
        run: python -m pytest backend/tests --cov=backend/app --cov-report=term-missing

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - run: echo "Deploy simulado"